package com.gpms.dao.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName("college")
public class College {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`id`")
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.name
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.major_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer majorNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.teacher_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer teacherNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.student_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.desc
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`desc`")
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column college.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public College(Integer id, String name, Integer majorNumber, Integer teacherNumber, Integer studentNumber, String desc, Date updateTime, Date createTime) {
        this.id = id;
        this.name = name;
        this.majorNumber = majorNumber;
        this.teacherNumber = teacherNumber;
        this.studentNumber = studentNumber;
        this.desc = desc;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table college
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public College() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.id
     *
     * @return the value of college.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.id
     *
     * @param id the value for college.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.name
     *
     * @return the value of college.name
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.name
     *
     * @param name the value for college.name
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.major_number
     *
     * @return the value of college.major_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getMajorNumber() {
        return majorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.major_number
     *
     * @param majorNumber the value for college.major_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setMajorNumber(Integer majorNumber) {
        this.majorNumber = majorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.teacher_number
     *
     * @return the value of college.teacher_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getTeacherNumber() {
        return teacherNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.teacher_number
     *
     * @param teacherNumber the value for college.teacher_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setTeacherNumber(Integer teacherNumber) {
        this.teacherNumber = teacherNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.student_number
     *
     * @return the value of college.student_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.student_number
     *
     * @param studentNumber the value for college.student_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.desc
     *
     * @return the value of college.desc
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.desc
     *
     * @param desc the value for college.desc
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.update_time
     *
     * @return the value of college.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.update_time
     *
     * @param updateTime the value for college.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column college.create_time
     *
     * @return the value of college.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column college.create_time
     *
     * @param createTime the value for college.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}