package com.gpms.dao.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName("file")
public class FileInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    @TableField("`id`")
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.owner
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private Integer owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.name
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.extension
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.path
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.size
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private Integer size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.update_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.create_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public FileInfo(Integer id, Integer owner, String name, String extension, String path, Integer size, Date updateTime, Date createTime) {
        this.id = id;
        this.owner = owner;
        this.name = name;
        this.extension = extension;
        this.path = path;
        this.size = size;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public FileInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.owner
     *
     * @return the value of file.owner
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.owner
     *
     * @param owner the value for file.owner
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.name
     *
     * @return the value of file.name
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.name
     *
     * @param name the value for file.name
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.extension
     *
     * @return the value of file.extension
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.extension
     *
     * @param extension the value for file.extension
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.path
     *
     * @return the value of file.path
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.path
     *
     * @param path the value for file.path
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.size
     *
     * @return the value of file.size
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.size
     *
     * @param size the value for file.size
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.update_time
     *
     * @return the value of file.update_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.update_time
     *
     * @param updateTime the value for file.update_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.create_time
     *
     * @return the value of file.create_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.create_time
     *
     * @param createTime the value for file.create_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}