package com.gpms.dao.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName("major")
public class Major {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`id`")
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.code
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.name
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.desc
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`desc`")
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.class_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer classNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.teacher_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer teacherNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.student_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.college
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column major.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Major(Integer id, String code, String name, String desc, Integer classNumber, Integer teacherNumber, Integer studentNumber, Integer college, Date updateTime, Date createTime) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.desc = desc;
        this.classNumber = classNumber;
        this.teacherNumber = teacherNumber;
        this.studentNumber = studentNumber;
        this.college = college;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Major() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.id
     *
     * @return the value of major.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.id
     *
     * @param id the value for major.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.code
     *
     * @return the value of major.code
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.code
     *
     * @param code the value for major.code
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.name
     *
     * @return the value of major.name
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.name
     *
     * @param name the value for major.name
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.desc
     *
     * @return the value of major.desc
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.desc
     *
     * @param desc the value for major.desc
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.class_number
     *
     * @return the value of major.class_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getClassNumber() {
        return classNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.class_number
     *
     * @param classNumber the value for major.class_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setClassNumber(Integer classNumber) {
        this.classNumber = classNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.teacher_number
     *
     * @return the value of major.teacher_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getTeacherNumber() {
        return teacherNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.teacher_number
     *
     * @param teacherNumber the value for major.teacher_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setTeacherNumber(Integer teacherNumber) {
        this.teacherNumber = teacherNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.student_number
     *
     * @return the value of major.student_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.student_number
     *
     * @param studentNumber the value for major.student_number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setStudentNumber(Integer studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.college
     *
     * @return the value of major.college
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.college
     *
     * @param college the value for major.college
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCollege(Integer college) {
        this.college = college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.update_time
     *
     * @return the value of major.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.update_time
     *
     * @param updateTime the value for major.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column major.create_time
     *
     * @return the value of major.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column major.create_time
     *
     * @param createTime the value for major.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}