package com.gpms.dao.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName("notice")
public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`id`")
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.author
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.reviewer
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer reviewer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content_short
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String contentShort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.importance
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Byte importance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.type
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.status
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`status`")
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.display_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date displayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.comment_disabled
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Boolean commentDisabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.view_times
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer viewTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.img_uri
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String imgUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Notice(Integer id, String title, Integer author, Integer reviewer, String contentShort, Byte importance, Integer type, Integer status, Date displayTime, Boolean commentDisabled, Integer viewTimes, String imgUri, Date updateTime, Date createTime, String content) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.reviewer = reviewer;
        this.contentShort = contentShort;
        this.importance = importance;
        this.type = type;
        this.status = status;
        this.displayTime = displayTime;
        this.commentDisabled = commentDisabled;
        this.viewTimes = viewTimes;
        this.imgUri = imgUri;
        this.updateTime = updateTime;
        this.createTime = createTime;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Notice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.author
     *
     * @return the value of notice.author
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.author
     *
     * @param author the value for notice.author
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.reviewer
     *
     * @return the value of notice.reviewer
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.reviewer
     *
     * @param reviewer the value for notice.reviewer
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setReviewer(Integer reviewer) {
        this.reviewer = reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.content_short
     *
     * @return the value of notice.content_short
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getContentShort() {
        return contentShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.content_short
     *
     * @param contentShort the value for notice.content_short
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setContentShort(String contentShort) {
        this.contentShort = contentShort == null ? null : contentShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.importance
     *
     * @return the value of notice.importance
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Byte getImportance() {
        return importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.importance
     *
     * @param importance the value for notice.importance
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setImportance(Byte importance) {
        this.importance = importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.type
     *
     * @return the value of notice.type
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.type
     *
     * @param type the value for notice.type
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.status
     *
     * @return the value of notice.status
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.status
     *
     * @param status the value for notice.status
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.display_time
     *
     * @return the value of notice.display_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getDisplayTime() {
        return displayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.display_time
     *
     * @param displayTime the value for notice.display_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setDisplayTime(Date displayTime) {
        this.displayTime = displayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.comment_disabled
     *
     * @return the value of notice.comment_disabled
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Boolean getCommentDisabled() {
        return commentDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.comment_disabled
     *
     * @param commentDisabled the value for notice.comment_disabled
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCommentDisabled(Boolean commentDisabled) {
        this.commentDisabled = commentDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.view_times
     *
     * @return the value of notice.view_times
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getViewTimes() {
        return viewTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.view_times
     *
     * @param viewTimes the value for notice.view_times
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setViewTimes(Integer viewTimes) {
        this.viewTimes = viewTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.img_uri
     *
     * @return the value of notice.img_uri
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getImgUri() {
        return imgUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.img_uri
     *
     * @param imgUri the value for notice.img_uri
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setImgUri(String imgUri) {
        this.imgUri = imgUri == null ? null : imgUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.update_time
     *
     * @return the value of notice.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.update_time
     *
     * @param updateTime the value for notice.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.create_time
     *
     * @return the value of notice.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.create_time
     *
     * @param createTime the value for notice.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.content
     *
     * @return the value of notice.content
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.content
     *
     * @param content the value for notice.content
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}