package com.gpms.dao.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName("private_notice")
public class PrivateNotice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_notice.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`id`")
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_notice.owner
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_notice.receiver
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_notice.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_notice.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_notice
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public PrivateNotice(Integer id, Integer owner, Integer receiver, Date updateTime, Date createTime) {
        this.id = id;
        this.owner = owner;
        this.receiver = receiver;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_notice
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public PrivateNotice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_notice.id
     *
     * @return the value of private_notice.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_notice.id
     *
     * @param id the value for private_notice.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_notice.owner
     *
     * @return the value of private_notice.owner
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_notice.owner
     *
     * @param owner the value for private_notice.owner
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_notice.receiver
     *
     * @return the value of private_notice.receiver
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_notice.receiver
     *
     * @param receiver the value for private_notice.receiver
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_notice.update_time
     *
     * @return the value of private_notice.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_notice.update_time
     *
     * @param updateTime the value for private_notice.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_notice.create_time
     *
     * @return the value of private_notice.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_notice.create_time
     *
     * @param createTime the value for private_notice.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}