package com.gpms.dao.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName("project")
public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    @TableField("`id`")
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.teacher
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private Integer teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.title
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.student
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private Integer student;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.create_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.content
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Project(Integer id, Integer teacher, String title, Integer status, Integer student, Date updateTime, Date createTime, String content) {
        this.id = id;
        this.teacher = teacher;
        this.title = title;
        this.status = status;
        this.student = student;
        this.updateTime = updateTime;
        this.createTime = createTime;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Project() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.teacher
     *
     * @return the value of project.teacher
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Integer getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.teacher
     *
     * @param teacher the value for project.teacher
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setTeacher(Integer teacher) {
        this.teacher = teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.title
     *
     * @return the value of project.title
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.title
     *
     * @param title the value for project.title
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.status
     *
     * @return the value of project.status
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.status
     *
     * @param status the value for project.status
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.student
     *
     * @return the value of project.student
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Integer getStudent() {
        return student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.student
     *
     * @param student the value for project.student
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setStudent(Integer student) {
        this.student = student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_time
     *
     * @return the value of project.update_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_time
     *
     * @param updateTime the value for project.update_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.create_time
     *
     * @return the value of project.create_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.create_time
     *
     * @param createTime the value for project.create_time
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.content
     *
     * @return the value of project.content
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.content
     *
     * @param content the value for project.content
     *
     * @mbg.generated Fri Apr 12 16:31:54 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}