package com.gpms.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName("comment")
public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`id`")
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.author
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.mark
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content_short
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String contentShort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.status
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`status`")
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.target
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_disabled
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Boolean commentDisabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.view_times
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer viewTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.img_uri
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String imgUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Comment(Integer id, Integer author, Integer mark, String contentShort, Integer type, Integer status, Integer target, Boolean commentDisabled, Integer viewTimes, String imgUri, Date updateTime, Date createTime, String content) {
        this.id = id;
        this.author = author;
        this.mark = mark;
        this.contentShort = contentShort;
        this.type = type;
        this.status = status;
        this.target = target;
        this.commentDisabled = commentDisabled;
        this.viewTimes = viewTimes;
        this.imgUri = imgUri;
        this.updateTime = updateTime;
        this.createTime = createTime;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Comment() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.author
     *
     * @return the value of comment.author
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.author
     *
     * @param author the value for comment.author
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setAuthor(Integer author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.mark
     *
     * @return the value of comment.mark
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.mark
     *
     * @param mark the value for comment.mark
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content_short
     *
     * @return the value of comment.content_short
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getContentShort() {
        return contentShort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content_short
     *
     * @param contentShort the value for comment.content_short
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setContentShort(String contentShort) {
        this.contentShort = contentShort == null ? null : contentShort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.status
     *
     * @return the value of comment.status
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.status
     *
     * @param status the value for comment.status
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.target
     *
     * @return the value of comment.target
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.target
     *
     * @param target the value for comment.target
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setTarget(Integer target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_disabled
     *
     * @return the value of comment.comment_disabled
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Boolean getCommentDisabled() {
        return commentDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_disabled
     *
     * @param commentDisabled the value for comment.comment_disabled
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCommentDisabled(Boolean commentDisabled) {
        this.commentDisabled = commentDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.view_times
     *
     * @return the value of comment.view_times
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getViewTimes() {
        return viewTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.view_times
     *
     * @param viewTimes the value for comment.view_times
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setViewTimes(Integer viewTimes) {
        this.viewTimes = viewTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.img_uri
     *
     * @return the value of comment.img_uri
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getImgUri() {
        return imgUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.img_uri
     *
     * @param imgUri the value for comment.img_uri
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setImgUri(String imgUri) {
        this.imgUri = imgUri == null ? null : imgUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.update_time
     *
     * @return the value of comment.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.update_time
     *
     * @param updateTime the value for comment.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}