package com.gpms.domain.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;

@TableName("teacher_title")
public class TeacherTitle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_title.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`id`")
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_title.name
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_title.desc
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    @TableField("`desc`")
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_title.number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_title.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_title.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_title
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public TeacherTitle(Integer id, String name, String desc, Integer number, Date updateTime, Date createTime) {
        this.id = id;
        this.name = name;
        this.desc = desc;
        this.number = number;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_title
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public TeacherTitle() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_title.id
     *
     * @return the value of teacher_title.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_title.id
     *
     * @param id the value for teacher_title.id
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_title.name
     *
     * @return the value of teacher_title.name
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_title.name
     *
     * @param name the value for teacher_title.name
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_title.desc
     *
     * @return the value of teacher_title.desc
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_title.desc
     *
     * @param desc the value for teacher_title.desc
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_title.number
     *
     * @return the value of teacher_title.number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_title.number
     *
     * @param number the value for teacher_title.number
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_title.update_time
     *
     * @return the value of teacher_title.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_title.update_time
     *
     * @param updateTime the value for teacher_title.update_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_title.create_time
     *
     * @return the value of teacher_title.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_title.create_time
     *
     * @param createTime the value for teacher_title.create_time
     *
     * @mbg.generated Fri Apr 05 15:17:56 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}